### ISSUE TITLE
require('puzzle-microfrontends') failing

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [puzzle-js/puzzle-js#105]
With,
`
> node ./index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'base'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Volumes/Backup/Workspace/netflix-micro-frontend/layout-service/node_modules/puzzle-microfrontends/dist/index.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`

I think it's due to `require("base");` in the `dist\index.js`, removing this working fine

**Comment by Acanguven** [comment]
Fixed with https://github.com/puzzle-js/puzzle-js/releases/tag/3.30.2
